name = "WaveFront"
uuid = "4ae9afef-6ced-4cf1-b1c9-94587f855297"
authors = ["William Tegtow <w.tegtow@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.15.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["Test"]
